[build]
  publish = "webapp"
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[[headers]]
  for = "/admin.html"
  [headers.values]
    Cache-Control = "no-store"

[[redirects]]
  from = "/admin"
  to = "/admin.html"
  status = 200
